import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import FooterRenderer from "@/components/layout/Footer/FooterRenderer";
import HeaderRenderer from "@/components/layout/Header/HeaderRenderer";

const pretendardBold = localFont({
  src: "/fonts/Pretendard-ExtraBold.ttf", // public 폴더를 기준으로 설정
  variable: "--font-pretendard",
  weight: "100 900",
});

const pretendardRegular = localFont({
  src: '/fonts/Pretendard-Regular.ttf',
  variable: '--font-pretendard-regular',
  weight: '400',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pretendardRegular.variable} ${pretendardBold.variable}`}
        style={{ display: "flex", flexDirection: "column", height: "100vh" }}
      >
        <div className="layout-container">
          {/* Header 추가 */}
          <header className="header-container">
            <HeaderRenderer />
          </header>

          {/* 페이지 콘텐츠 */}
          <main style={{ flex: "1", width: "100%" }}>{children}</main>

          {/* FooterRenderer로 Footer 렌더링 */}
          <footer className="footer-container">
            <FooterRenderer />
          </footer>
        </div>
      </body>
    </html>
  );
}
